Repository SchedulAI/SchedulAI, pull requests merged in 2024-10, with the labels that each got.

#1 Created user registration logic and user login logic and routes
  Backend/.gitignore
  Backend/package-lock.json
  Backend/package.json
  Backend/src/config/.gitkeep
  Backend/src/config/index.ts
  Backend/src/controller/.gitkeep
  Backend/src/controller/loginController.ts
  Backend/src/controller/userController.ts
  Backend/src/db/.gitkeep
  Backend/src/db/index.ts
  Backend/src/index.ts
  Backend/src/middleware/.gitkeep
  Backend/src/middleware/asyncHandle.ts
  Backend/src/middleware/permissionVerify.ts
  Backend/src/repository/.gitkeep
  Backend/src/repository/loginRepository.ts
  Backend/src/repository/userRepository.ts
  Backend/src/routes/.gitkeep
  Backend/src/routes/loginRoutes.ts
  Backend/src/routes/routes.ts
  Backend/src/routes/userRoutes.ts
  Backend/src/services/.gitkeep
  Backend/src/services/loginServices.ts
  Backend/src/services/userService.ts
  Backend/src/utils/.gitkeep
  Backend/src/utils/comparePassword.ts
  Backend/src/utils/hashPassword.ts
Labels: enhancement

#2 Created some frontend components
  Frontend/index.html
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/public/vite.svg
  Frontend/src/App.css
  Frontend/src/App.tsx
  Frontend/src/assets/react.svg
  Frontend/src/components/Button/button.css
  Frontend/src/components/Button/index.tsx
  Frontend/src/components/Card/card.css
  Frontend/src/components/Card/index.tsx
  Frontend/src/components/Checkbox/checkbox.css
  Frontend/src/components/Checkbox/index.tsx
  Frontend/src/components/Icon/index.tsx
  Frontend/src/components/Input/index.tsx
  Frontend/src/components/Input/input.css
  Frontend/src/index.css
  Frontend/tsconfig.app.tsbuildinfo
  Frontend/tsconfig.node.tsbuildinfo
Labels: enhancement

#3 Implement migrate method for running database migrations
  Backend/.env_example
  Backend/package-lock.json
  Backend/package.json
  Backend/src/db/migrations/001_create_user_table.sql
  Backend/src/db/migrations/002_create_schedule_table.sql
  Backend/src/db/migrations/003_create_invites_table.sql
  Backend/src/db/migrations/004_create_proposed_date_table.sql
  Backend/src/db/migrations/005_create_availability_table.sql
  Backend/src/db/migrations/006_create_dialogs_table.sql
  Backend/src/db/migrations/007_create_messages_table.sql
  Backend/src/db/migrations/008_create_notifications_table.sql
  Backend/src/db/runMigrations.ts
  Backend/tsconfig.json
Labels: enhancement

#4 Alter tables to generate uuid
  Backend/src/db/migrations/009_alter_tables_to_generate_uuid.sql
Labels: enhancement

#6 Home page and login page, routes, user context
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.css
  Frontend/src/App.tsx
  Frontend/src/components/Button/button.css
  Frontend/src/components/Icon/index.tsx
  Frontend/src/components/Input/index.tsx
  Frontend/src/hooks/userHooks.ts
  Frontend/src/index.css
  Frontend/src/pages/Error404/index.tsx
  Frontend/src/pages/Home/index.tsx
  Frontend/src/pages/Home/style.css
  Frontend/src/pages/Login/index.tsx
  Frontend/src/pages/Login/style.css
  Frontend/src/providers/UserProvider.tsx
  Frontend/src/routes/routes.tsx
Labels: enhancement

#5 feat and fix: implement create methods to schedule crud and fix permissionVerify middleware return
  Backend/package-lock.json
  Backend/package.json
  Backend/src/controller/scheduleController.ts
  Backend/src/index.ts
  Backend/src/middleware/permissionVerify.ts
  Backend/src/repository/scheduleRepository.ts
  Backend/src/routes/routes.ts
  Backend/src/routes/scheduleRoutes.ts
  Backend/src/services/scheduleServices.ts
Labels: enhancement

#8 Frontend/feature/converte components styled
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/App.tsx
  Frontend/src/components/Button/button.css
  Frontend/src/components/Button/index.tsx
  Frontend/src/components/Card/card.css
  Frontend/src/components/Card/index.tsx
  Frontend/src/components/Checkbox/checkbox.css
  Frontend/src/components/Checkbox/index.tsx
  Frontend/src/components/Input/index.tsx
  Frontend/src/components/Input/input.css
  Frontend/src/index.css
  Frontend/src/pages/Home/index.tsx
  package-lock.json
Labels: enhancement

#9 Frontend/feature/converte home styled
  Frontend/src/App.css
  Frontend/src/components/Button/index.tsx
  Frontend/src/index.css
  Frontend/src/pages/Home/index.tsx
  Frontend/src/pages/Login/index.tsx
Labels: enhancement

#10 frontend/feature: navbar
  Frontend/index.html
  Frontend/src/components/Navbar/index.tsx
  Frontend/src/index.css
  Frontend/src/main.tsx
  Frontend/src/pages/Home/index.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/src/styles/globalStyles.tsx
  Frontend/tsconfig.app.tsbuildinfo
Labels: enhancement

#11 feat: initial ai chat
  Backend/src/controller/chatController.ts
  Backend/src/db/migrations/010_alter_messages_table_to_have_created_at.sql
  Backend/src/db/migrations/011_alter_messages_table_to_rename_column_sender_type.sql
  Backend/src/db/migrations/012_alter_messages_table_to_change_message_type.sql
  Backend/src/repository/dialogRepository.ts
  Backend/src/routes/chatRoutes.ts
  Backend/src/routes/routes.ts
  Backend/src/services/chatServices.ts
Labels: enhancement

#12 feat and refactor: implement logout feature and refactor some imports and remove asyncHandle
  Backend/src/controller/loginController.ts
  Backend/src/controller/userController.ts
  Backend/src/middleware/asyncHandle.ts
  Backend/src/routes/loginRoutes.ts
  Backend/src/routes/routes.ts
  Backend/src/routes/userRoutes.ts
  Backend/src/services/loginServices.ts
Labels: enhancement

#13 frontend/feature: create register page
  Frontend/src/pages/Login/index.tsx
  Frontend/src/pages/Login/style.css
  Frontend/src/pages/Register/index.tsx
  Frontend/src/routes/routes.tsx
Labels: enhancement

#14 Created dashboard page
  Backend/src/index.ts
  Frontend/src/components/Button/index.tsx
  Frontend/src/components/Icon/index.tsx
  Frontend/src/components/Navbar/index.tsx
  Frontend/src/components/Snackbar/index.tsx
  Frontend/src/pages/Dashboard/index.tsx
  Frontend/src/pages/Home/index.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/src/routes/routes.tsx
Labels: enhancement

#15 Adjust api environment logic and adjust register page to connect with the api
  Backend/src/repository/userRepository.ts
  Frontend/.gitignore
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/components/Icon/index.tsx
  Frontend/src/components/Input/index.tsx
  Frontend/src/config/api.ts
  Frontend/src/pages/Dashboard/index.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/src/pages/Register/index.tsx
Labels: enhancement

#16 feat: add getMessagesByDialogId
  Backend/src/controller/dialogController.ts
  Backend/src/routes/dialogRoutes.ts
  Backend/src/routes/routes.ts
  Backend/src/services/dialogServices.ts
Labels: enhancement

#18 fix and feat adjusted the authentication verification route and integrated it with the frontend and also created the slide menu
  Backend/src/controller/loginController.ts
  Backend/src/routes/loginRoutes.ts
  Frontend/.prettierrc
  Frontend/index.html
  Frontend/src/Utils/ValidateAuth.tsx
  Frontend/src/assets/icons/favicon.svg
  Frontend/src/components/Icon/index.tsx
  Frontend/src/components/Navbar/index.tsx
  Frontend/src/hooks/userHooks.ts
  Frontend/src/pages/Dashboard/index.tsx
  Frontend/src/pages/Home/index.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/src/routes/routes.tsx
Labels: enhancement, invalid

#19 Refactoring and small fixes
  Backend/src/controller/chatController.ts
  Backend/src/controller/dialogController.ts
  Backend/src/controller/loginController.ts
  Backend/src/controller/scheduleController.ts
  Backend/src/controller/userController.ts
  Backend/src/db/index.ts
  Backend/src/entities/dialogEntity.ts
  Backend/src/entities/messageEntity.ts
  Backend/src/entities/scheduleEntity.ts
  Backend/src/entities/userEntity.ts
  Backend/src/index.ts
  Backend/src/middleware/permissionVerify.ts
  Backend/src/repository/dialogRepository.ts
  Backend/src/repository/loginRepository.ts
  Backend/src/repository/scheduleRepository.ts
  Backend/src/repository/userRepository.ts
  Backend/src/routes/chatRoutes.ts
  Backend/src/routes/dialogRoutes.ts
  Backend/src/routes/loginRoutes.ts
  Backend/src/routes/scheduleRoutes.ts
  Backend/src/routes/userRoutes.ts
  Backend/src/services/chatServices.ts
  Backend/src/services/dialogServices.ts
  Backend/src/services/loginServices.ts
  Backend/src/services/scheduleServices.ts
  Backend/src/services/userService.ts
  Backend/src/utils/errorResponse.ts
  Backend/src/utils/exceptions.ts
  Backend/src/utils/hashPassword.ts
  Backend/src/utils/http_response.ts
  Backend/src/utils/llm.ts
Labels: enhancement

#20 feat: add backend prettier and indentations and add validateToken back
  Backend/.prettierrc
  Backend/src/config/index.ts
  Backend/src/controller/chatController.ts
  Backend/src/controller/dialogController.ts
  Backend/src/controller/loginController.ts
  Backend/src/controller/scheduleController.ts
  Backend/src/controller/userController.ts
  Backend/src/db/index.ts
  Backend/src/db/runMigrations.ts
  Backend/src/entities/dialogEntity.ts
  Backend/src/entities/messageEntity.ts
  Backend/src/entities/scheduleEntity.ts
  Backend/src/entities/userEntity.ts
  Backend/src/index.ts
  Backend/src/middleware/permissionVerify.ts
  Backend/src/repository/dialogRepository.ts
  Backend/src/repository/loginRepository.ts
  Backend/src/repository/scheduleRepository.ts
  Backend/src/repository/userRepository.ts
  Backend/src/routes/chatRoutes.ts
  Backend/src/routes/dialogRoutes.ts
  Backend/src/routes/loginRoutes.ts
  Backend/src/routes/routes.ts
  Backend/src/routes/scheduleRoutes.ts
  Backend/src/routes/userRoutes.ts
  Backend/src/services/chatServices.ts
  Backend/src/services/dialogServices.ts
  Backend/src/services/loginServices.ts
  Backend/src/services/scheduleServices.ts
  Backend/src/services/userService.ts
  Backend/src/utils/comparePassword.ts
  Backend/src/utils/errorResponse.ts
  Backend/src/utils/exceptions.ts
  Backend/src/utils/hashPassword.ts
  Backend/src/utils/http_response.ts
  Backend/src/utils/llm.ts
Labels: enhancement

#22 feat: implements history to AI chat
  Backend/package-lock.json
  Backend/package.json
  Backend/src/repository/dialogRepository.ts
  Backend/src/services/chatServices.ts
  Backend/src/utils/llm.ts
Labels: enhancement

#23 feat and refactor: implement schedule cancel route and refactor schedule table
  Backend/src/controller/scheduleController.ts
  Backend/src/db/migrations/013_alter_schedule_table_to_remove_schedule_date.sql
  Backend/src/db/migrations/014_alter_schedule_table_to_add_duration_column.sql
  Backend/src/db/migrations/015_alter_schedule_table_to_add_status_default_value.sql
  Backend/src/entities/scheduleEntity.ts
  Backend/src/repository/scheduleRepository.ts
  Backend/src/routes/scheduleRoutes.ts
  Backend/src/services/scheduleServices.ts
Labels: enhancement

#25 feat: add interfaces to front end
  Frontend/src/interfaces/ApiResponse.ts
  Frontend/src/interfaces/Dialog.ts
  Frontend/src/interfaces/Message.ts
  Frontend/src/interfaces/Schedule.ts
  Frontend/src/interfaces/User.ts
Labels: enhancement

#24 refactor chat controller and services
  Backend/src/controller/chatController.ts
  Backend/src/services/chatServices.ts
  Frontend/src/pages/Dashboard/index.tsx
Labels: enhancement

#26 Created recovery password page and added schedule cards in the dashboard page
  Frontend/src/components/Card/index.tsx
  Frontend/src/components/Icon/index.tsx
  Frontend/src/pages/Dashboard/index.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/src/pages/RecoverPassword/index.tsx
  Frontend/src/pages/Register/index.tsx
  Frontend/src/routes/routes.tsx
  Frontend/src/types/schedules.d.ts
Labels: enhancement

#27 Added Registration call page and made some fix in snackbar.
  Frontend/src/App.tsx
  Frontend/src/components/Snackbar/index.tsx
  Frontend/src/hooks/scheduleHooks.ts
  Frontend/src/pages/InvitedRegister/index.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/src/pages/Register/index.tsx
  Frontend/src/providers/ScheduleProvider.tsx
  Frontend/src/routes/routes.tsx
  Frontend/src/types/schedules.d.ts
Labels: enhancement

#29 Update schedule info ai tool
  Backend/package-lock.json
  Backend/package.json
  Backend/src/controller/scheduleController.ts
  Backend/src/entities/messageEntity.ts
  Backend/src/repository/dialogRepository.ts
  Backend/src/repository/scheduleRepository.ts
  Backend/src/routes/scheduleRoutes.ts
  Backend/src/services/chatServices.ts
  Backend/src/services/scheduleServices.ts
  Backend/src/utils/llm.ts
  Backend/src/utils/tools.ts
  Frontend/src/interfaces/Message.ts
Labels: enhancement

#32 Adjusting fetches and better file organization
  Frontend/src/Utils/FormatDate.ts
  Frontend/src/Utils/HandleStatus.ts
  Frontend/src/Utils/RenderDateInfo.ts
  Frontend/src/components/Button/Button.d.ts
  Frontend/src/components/Button/StyledButton.tsx
  Frontend/src/components/Button/index.tsx
  Frontend/src/components/Card/Card.d.ts
  Frontend/src/components/Card/CardStyled.tsx
  Frontend/src/components/Card/index.tsx
  Frontend/src/components/Checkbox/Checkbox.d.ts
  Frontend/src/components/Checkbox/CheckboxStyled.tsx
  Frontend/src/components/Checkbox/index.tsx
  Frontend/src/components/Icon/Icon.d.ts
  Frontend/src/components/Icon/index.tsx
  Frontend/src/components/Input/InputStyled.tsx
  Frontend/src/components/Input/index.tsx
  Frontend/src/components/Input/input.d.ts
  Frontend/src/components/Modal/Modal.d.ts
  Frontend/src/components/Modal/ModalStyled.tsx
  Frontend/src/components/Modal/index.tsx
  Frontend/src/components/Navbar/NavbarStyled.tsx
  Frontend/src/components/Navbar/index.tsx
  Frontend/src/components/Snackbar/Snackbar.d.ts
  Frontend/src/components/Snackbar/SnackbarContainer.tsx
  Frontend/src/components/Snackbar/index.tsx
  Frontend/src/interfaces/ApiResponse.d.ts
  Frontend/src/interfaces/Dialog.d.ts
  Frontend/src/interfaces/Message.d.ts
  Frontend/src/interfaces/Message.ts
  Frontend/src/interfaces/Register.d.ts
  Frontend/src/interfaces/Schedule.d.ts
  Frontend/src/interfaces/Schedule.ts
  Frontend/src/interfaces/User.d.ts
  Frontend/src/pages/Dashboard/StyleDashbord.tsx
  Frontend/src/pages/Dashboard/index.tsx
  Frontend/src/pages/Error404/StyledError404.tsx
  Frontend/src/pages/Error404/index.tsx
  Frontend/src/pages/Home/HomeStyled.tsx
  Frontend/src/pages/Home/index.tsx
  Frontend/src/pages/Home/style.css
  Frontend/src/pages/InvitedRegister/InvitedStyled.tsx
  Frontend/src/pages/InvitedRegister/index.tsx
  Frontend/src/pages/Login/LoginStyled.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/src/pages/RecoverPassword/RecoverPasswordStyled.tsx
  Frontend/src/pages/RecoverPassword/index.tsx
  Frontend/src/pages/Register/RegisterStyled.tsx
  Frontend/src/pages/Register/index.tsx
  Frontend/src/types/schedules.d.ts
Labels: enhancement

#36 Create availabilities ai tool
  Backend/src/entities/messageEntity.ts
  Backend/src/repository/dialogRepository.ts
  Backend/src/schemas/availability.ts
  Backend/src/services/chatServices.ts
  Backend/src/services/dialogServices.ts
  Backend/src/utils/llm.ts
  Backend/src/utils/tools.ts
Labels: enhancement

#37 Front adjust schedule route logic
  Backend/src/controller/proposedDateController.ts
  Backend/src/controller/scheduleController.ts
  Frontend/src/Utils/FormatMessage.tsx
  Frontend/src/Utils/HandleStatus.ts
  Frontend/src/Utils/RenderDateInfo.ts
  Frontend/src/Utils/sortSchedules.ts
  Frontend/src/components/Card/Card.d.ts
  Frontend/src/components/Card/index.tsx
  Frontend/src/components/Modal/Modal.d.ts
  Frontend/src/components/Modal/ModalStyled.tsx
  Frontend/src/components/Modal/index.tsx
  Frontend/src/interfaces/Schedule.d.ts
  Frontend/src/pages/Dashboard/StyleDashboard.tsx
  Frontend/src/pages/Dashboard/index.tsx
  Frontend/src/types/schedules.d.ts
Labels: enhancement, invalid

#38 refactor: refactors the organization of tool files
  Backend/src/schemas/availability.ts
  Backend/src/schemas/invitedEmails.ts
  Backend/src/schemas/updateScheduleInfo.ts
  Backend/src/tools/createAvailabilities.ts
  Backend/src/tools/createInvitedEmails.ts
  Backend/src/tools/tools.ts
  Backend/src/tools/updateScheduleInfo.ts
  Backend/src/utils/llm.ts
  Backend/src/utils/tools.ts
Labels: enhancement

#39 Create invites ai tool
  Backend/src/services/chatServices.ts
  Backend/src/services/invitesServices.ts
  Backend/src/tools/createInvitedEmails.ts
  Backend/src/tools/createInvites.ts
  Backend/src/tools/tools.ts
  Backend/src/utils/llm.ts
Labels: enhancement

#42 Made some changes in the dashboard style and created a logic to implement some cookies to make a custom control for the first time user.
  Frontend/src/Utils/Cookies.ts
  Frontend/src/components/Modal/ModalStyled.tsx
  Frontend/src/components/Modal/index.tsx
  Frontend/src/pages/Dashboard/StyleDashboard.tsx
  Frontend/src/pages/Dashboard/index.tsx
  Frontend/src/pages/Register/index.tsx
Labels: enhancement

#44 frontend/feature: footer
  Frontend/src/components/Footer/FooterStyled.tsx
  Frontend/src/components/Footer/index.tsx
  Frontend/src/components/Icon/Icon.d.ts
  Frontend/src/components/Icon/index.tsx
  Frontend/src/pages/Home/index.tsx
Labels: enhancement

#45 Fix styled dashboard and made some changes in the snackbar
  Frontend/src/Utils/HandleStatus.ts
  Frontend/src/components/Snackbar/Snackbar.d.ts
  Frontend/src/components/Snackbar/SnackbarContainer.tsx
  Frontend/src/components/Snackbar/StyledSnackbar.tsx
  Frontend/src/components/Snackbar/index.tsx
  Frontend/src/interfaces/Register.d.ts
  Frontend/src/pages/Dashboard/StyleDashboard.tsx
  Frontend/src/pages/Dashboard/index.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/src/pages/Register/index.tsx
Labels: enhancement, invalid

#46 Fixed the card to make them more friendly for the users
  Frontend/src/Utils/RenderDateInfo.ts
  Frontend/src/Utils/sortSchedules.ts
  Frontend/src/components/Card/CardStyled.tsx
  Frontend/src/components/Card/index.tsx
Labels: enhancement, invalid

#47 Made the modal more friendly for the users and adjusted some styles
  Frontend/src/Utils/HandleStatus.ts
  Frontend/src/assets/background/4861091.png
  Frontend/src/components/Card/CardStyled.tsx
  Frontend/src/components/Icon/Icon.d.ts
  Frontend/src/components/Icon/index.tsx
  Frontend/src/components/Modal/ModalStyled.tsx
  Frontend/src/components/Modal/index.tsx
  Frontend/src/pages/Dashboard/StyleDashboard.tsx
Labels: enhancement, invalid

#48 Added showdown to convert markdown to html
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/pages/Dashboard/StyleDashboard.tsx
  Frontend/src/pages/Dashboard/index.tsx
Labels: enhancement

#49 update-invite-status-ai-tool
  Backend/src/controller/invitesController.ts
  Backend/src/repository/invitesRepository.ts
  Backend/src/routes/scheduleRoutes.ts
  Backend/src/services/invitesServices.ts
  Backend/src/tools/createAvailabilities.ts
  Backend/src/tools/tools.ts
  Backend/src/tools/updateInviteStatus.ts
Labels: enhancement

#51 Initiated docker-compose and made some fixes on frontend and added a new env to the env file.
  Backend/.dockerignore
  Backend/.env_example
  Backend/Dockerfile
  Backend/src/config/index.ts
  Backend/src/index.ts
  Frontend/.dockerignore
  Frontend/.env-example
  Frontend/.gitignore
  Frontend/Dockerfile
  Frontend/src/components/Modal/index.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/src/pages/Register/index.tsx
  Frontend/tsconfig.app.tsbuildinfo
  docker-compose.yml
Labels: enhancement, invalid

#53 refactor some tools
  Backend/src/controller/availabilityController.ts
  Backend/src/db/migrations/020_alter_proposed_date_table.sql
  Backend/src/entities/availabilityEntity.ts
  Backend/src/repository/availabilityRepository.ts
  Backend/src/repository/proposedDateRepository.ts
  Backend/src/repository/scheduleRepository.ts
  Backend/src/routes/scheduleRoutes.ts
  Backend/src/services/availabilityServices.ts
  Backend/src/tools/createAvailabilities.ts
  Backend/src/tools/createInvites.ts
  Backend/src/tools/updateScheduleInfo.ts
  Backend/src/utils/llm.ts
Labels: enhancement

#52 Make some adjust in the code and create some components for the chat …
  Frontend/eslint.config.js
  Frontend/src/Utils/FormatMessage.tsx
  Frontend/src/components/Modal/Modal.d.ts
  Frontend/src/components/Modal/index.tsx
  Frontend/src/pages/Dashboard/Chat/Chat.d.ts
  Frontend/src/pages/Dashboard/Chat/ChatInput/Chatinput.d.ts
  Frontend/src/pages/Dashboard/Chat/ChatInput/index.tsx
  Frontend/src/pages/Dashboard/Chat/index.tsx
  Frontend/src/pages/Dashboard/SlideMenu/Sidemenu.d.ts
  Frontend/src/pages/Dashboard/SlideMenu/index.tsx
  Frontend/src/pages/Dashboard/StyleDashboard.tsx
  Frontend/src/pages/Dashboard/index.tsx
  Frontend/src/pages/Home/HomeStyled.tsx
  Frontend/src/pages/Home/index.tsx
  Frontend/src/pages/InvitedRegister/InvitedStyled.tsx
  Frontend/src/pages/Login/index.tsx
Labels: enhancement

#54 Created deleted route and integrated the logic on the modal, cards and dashboard
  Backend/src/controller/scheduleController.ts
  Backend/src/entities/scheduleEntity.ts
  Backend/src/repository/scheduleRepository.ts
  Backend/src/routes/scheduleRoutes.ts
  Backend/src/services/scheduleServices.ts
  Frontend/src/components/Card/Card.d.ts
  Frontend/src/components/Card/index.tsx
  Frontend/src/components/Modal/index.tsx
  Frontend/src/interfaces/Schedule.d.ts
  Frontend/src/pages/Dashboard/SlideMenu/index.tsx
Labels: enhancement

#55 Created the route to change the schedule status to reviewing, made some adjusts in the sidebar and modal.
  Backend/src/controller/scheduleController.ts
  Backend/src/repository/scheduleRepository.ts
  Backend/src/routes/scheduleRoutes.ts
  Backend/src/services/scheduleServices.ts
  Frontend/src/components/Modal/ModalStyled.tsx
  Frontend/src/components/Modal/index.tsx
  Frontend/src/pages/Dashboard/SlideMenu/index.tsx
  Frontend/src/pages/Dashboard/StyleDashboard.tsx
Labels: bug, enhancement

#56 Added a new info in getAllSchedules and adjust the frontend to recive the info
  Backend/src/services/scheduleServices.ts
  Frontend/src/components/Modal/index.tsx
  Frontend/src/interfaces/Schedule.d.ts
Labels: enhancement

#57 proposed date algorithm and some refactor
  Backend/src/db/migrations/020_alter_proposed_date_table.sql
  Backend/src/repository/availabilityRepository.ts
  Backend/src/services/dialogServices.ts
  Backend/src/tools/createAvailabilities.ts
  Backend/src/tools/createInvitedEmails.ts
  Backend/src/tools/createInvites.ts
  Backend/src/tools/updateInviteStatus.ts
  Backend/src/utils/findPossibleScheduleDates.ts
  Backend/src/utils/formatProposedDate.ts
  Backend/src/utils/llm.ts
Labels: enhancement

#58 refactor: refactor AI history system
  Backend/src/db/migrations/021_alter_message_table.sql
  Backend/src/entities/messageEntity.ts
  Backend/src/services/chatServices.ts
  Backend/src/services/dialogServices.ts
  Backend/src/services/invitesServices.ts
  Backend/src/tools/createInvites.ts
  Backend/src/tools/updateInviteStatus.ts
  Frontend/src/components/Modal/index.tsx
  Frontend/src/interfaces/Message.d.ts
  Frontend/src/pages/Dashboard/index.tsx
Labels: enhancement

#59 Frontend/feature/style adjustments
  Frontend/src/App.css
  Frontend/src/components/Button/StyledButton.tsx
  Frontend/src/components/Footer/FooterStyled.tsx
  Frontend/src/components/Footer/index.tsx
  Frontend/src/components/Navbar/NavbarStyled.tsx
  Frontend/src/index.css
  Frontend/src/main.tsx
  Frontend/src/pages/Home/HomeStyled.tsx
  Frontend/src/pages/Home/index.tsx
  Frontend/src/pages/Login/LoginStyled.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/src/pages/RecoverPassword/RecoverPasswordStyled.tsx
  Frontend/src/pages/RecoverPassword/index.tsx
  Frontend/src/pages/Register/RegisterStyled.tsx
  Frontend/src/pages/Register/index.tsx
  Frontend/src/styles/globalStyles.tsx
  Frontend/src/styles/theme.tsx
Labels: enhancement

#60 Adjust a new logic to verify if the user is logged and adjust the response from the chat route.
  Backend/src/controller/chatController.ts
  Backend/src/controller/loginController.ts
  Backend/src/services/loginServices.ts
  Backend/src/services/scheduleServices.ts
  Frontend/eslint.config.js
  Frontend/src/Utils/FormatTime.ts
  Frontend/src/components/Modal/index.tsx
  Frontend/src/components/Navbar/index.tsx
  Frontend/src/interfaces/Message.d.ts
  Frontend/src/pages/Dashboard/Chat/Chat.d.ts
  Frontend/src/pages/Dashboard/Chat/ChatInput/Chatinput.d.ts
  Frontend/src/pages/Dashboard/Chat/ChatInput/index.tsx
  Frontend/src/pages/Dashboard/Chat/index.tsx
  Frontend/src/pages/Dashboard/index.tsx
  Frontend/src/pages/Home/index.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/src/pages/Register/index.tsx
  Frontend/src/providers/UserProvider.tsx
Labels: enhancement

#61 New round and confirm schedule ai tool
  Backend/.dockerignore
  Backend/Dockerfile
  Backend/src/entities/proposedDateEntity.ts
  Backend/src/repository/availabilityRepository.ts
  Backend/src/repository/proposedDateRepository.ts
  Backend/src/tools/confirmSchedule.ts
  Backend/src/tools/newRound.ts
  Backend/src/tools/tools.ts
  Frontend/.dockerignore
  Frontend/.gitignore
  Frontend/Dockerfile
  Frontend/src/Utils/RenderDateInfo.ts
  Frontend/src/components/Modal/index.tsx
  docker-compose.yml
Labels: enhancement

#62 Create README.md
  README.md
Labels: documentation

#63 Frontend/feature/adjustment colors theme
  Frontend/src/components/Checkbox/CheckboxStyled.tsx
  Frontend/src/components/Modal/ModalStyled.tsx
  Frontend/src/components/Modal/index.tsx
  Frontend/src/components/Navbar/NavbarStyled.tsx
  Frontend/src/pages/Dashboard/SlideMenu/index.tsx
  Frontend/src/pages/Dashboard/StyleDashboard.tsx
  Frontend/src/pages/Login/LoginStyled.tsx
  Frontend/src/styles/theme.tsx
Labels: enhancement

#64 Adjusted the logic for the render of the dashboard button in homepage and adjusted a snackbar error on modal component
  Frontend/src/components/Modal/index.tsx
  Frontend/src/pages/Dashboard/Chat/ChatInput/index.tsx
  Frontend/src/pages/Dashboard/StyleDashboard.tsx
  Frontend/src/pages/Dashboard/index.tsx
Labels: bug, enhancement

#65 Change tha main text on home page
  Frontend/src/pages/Home/index.tsx
Labels: enhancement

#66 feat: implement a new proposed-date-algorithm
  Backend/src/repository/availabilityRepository.ts
  Backend/src/repository/invitesRepository.ts
  Backend/src/repository/proposedDateRepository.ts
  Backend/src/tools/confirmSchedule.ts
  Backend/src/tools/updateInviteStatus.ts
  Backend/src/utils/findPossibleScheduleDates.ts
  Backend/src/utils/formatProposedDate.ts
  Backend/src/utils/llm.ts
  Backend/src/utils/matchAvailabilities.ts
Labels: enhancement

#69 Update README.md
  README.md
Labels: documentation

#71 frontend/fix/card
  Backend/src/utils/formatProposedDate.ts
  Frontend/src/components/Card/Card.d.ts
  Frontend/src/components/Card/index.tsx
  Frontend/src/pages/Dashboard/SlideMenu/index.tsx
Labels: bug

#72 Made some small fix on the message "there is no event"
  Frontend/src/pages/Dashboard/SlideMenu/index.tsx
  Frontend/src/pages/Dashboard/SlideMenu/style.tsx
  Frontend/src/pages/Dashboard/index.tsx
Labels: invalid

#73 refactor: refactor some prompts and tool descriptions
  Backend/src/tools/confirmSchedule.ts
  Backend/src/tools/createInvitedEmails.ts
  Backend/src/tools/createInvites.ts
  Backend/src/tools/newRound.ts
  Backend/src/tools/updateInviteStatus.ts
  Backend/src/tools/updateScheduleInfo.ts
  Backend/src/utils/llm.ts
Labels: enhancement

#74 Added a route to make a long polling and adjust the route to the dashboard, made some logic changes for the chat response.
  Backend/src/controller/scheduleController.ts
  Backend/src/routes/scheduleRoutes.ts
  Frontend/nginx.conf
  Frontend/src/components/Icon/Icon.d.ts
  Frontend/src/components/Icon/index.tsx
  Frontend/src/components/Modal/index.tsx
  Frontend/src/interfaces/Schedule.d.ts
  Frontend/src/pages/Dashboard/SlideMenu/index.tsx
  Frontend/src/pages/Dashboard/SlideMenu/style.tsx
  Frontend/src/pages/Dashboard/index.tsx
  Frontend/src/pages/Login/index.tsx
Labels: enhancement, invalid

#75 Adjuste the logic for the polling route just return a boolean
  Backend/src/controller/scheduleController.ts
  Frontend/src/interfaces/Schedule.d.ts
  Frontend/src/pages/Dashboard/index.tsx
Labels: enhancement

#77 Frontend/feature/user experience improvement
  Frontend/src/components/Button/StyledButton.tsx
  Frontend/src/components/Button/index.tsx
  Frontend/src/components/Card/CardStyled.tsx
  Frontend/src/components/Footer/index.tsx
  Frontend/src/components/Icon/Icon.d.ts
  Frontend/src/components/Icon/index.tsx
  Frontend/src/components/Modal/ModalStyled.tsx
  Frontend/src/pages/Dashboard/Chat/ChatInput/index.tsx
  Frontend/src/pages/Dashboard/Chat/index.tsx
  Frontend/src/pages/Dashboard/StyleDashboard.tsx
  Frontend/src/pages/Dashboard/index.tsx
  Frontend/src/pages/Dashboard/style.tsx
  Frontend/src/pages/Register/index.tsx
  package-lock.json
Labels: enhancement

#78 fix and refactor: fix matchAvailabilities rejecteds bug and refactor proposed date message
  Backend/src/tools/updateInviteStatus.ts
  Backend/src/utils/formatProposedDate.ts
  Backend/src/utils/matchAvailabilities.ts
Labels: enhancement

#79 fix: fix newRound tool and prompt
  Backend/src/tools/newRound.ts
  Backend/src/utils/llm.ts
Labels: enhancement

#80 longpolling-fix-and-change-some-modal-style
  Backend/src/controller/scheduleController.ts
  Frontend/src/Utils/RenderDateInfo.ts
  Frontend/src/Utils/capitalizeFirstLetter.ts
  Frontend/src/components/Card/CardStyled.tsx
  Frontend/src/components/Modal/Modal.d.ts
  Frontend/src/components/Modal/ModalStyled.tsx
  Frontend/src/components/Modal/index.tsx
  Frontend/src/interfaces/Message.d.ts
  Frontend/src/interfaces/Schedule.d.ts
  Frontend/src/pages/Dashboard/SlideMenu/Sidemenu.d.ts
  Frontend/src/pages/Dashboard/SlideMenu/index.tsx
  Frontend/src/pages/Dashboard/index.tsx
Labels: bug, enhancement, invalid

#81 Fixed-chat-overflow-wrap
  Frontend/src/components/Modal/ModalStyled.tsx
  Frontend/src/components/Modal/index.tsx
  Frontend/src/pages/Dashboard/style.tsx
Labels: bug

#82 adjusted the register page password infos and made some changes for it appears
  Frontend/src/components/Button/StyledButton.tsx
  Frontend/src/components/Input/index.tsx
  Frontend/src/components/Input/input.d.ts
  Frontend/src/pages/Dashboard/Chat/ChatInput/index.tsx
  Frontend/src/pages/Dashboard/Chat/index.tsx
  Frontend/src/pages/Login/index.tsx
  Frontend/src/pages/Register/RegisterStyled.tsx
  Frontend/src/pages/Register/index.tsx
Labels: enhancement

#83 fixed some small bugs
  Frontend/src/components/Snackbar/Snackbar.d.ts
  Frontend/src/components/Snackbar/SnackbarContainer.tsx
  Frontend/src/components/Snackbar/index.tsx
  Frontend/src/pages/Dashboard/style.tsx
  Frontend/src/pages/Register/index.tsx
Labels: bug
